# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('parent', 'code')]),
        ),
    ]
