# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0002_auto_20160902_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
