# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0003_auto_20160902_1524'),
    ]

    operations = [
        migrations.RenameField('Account', 'type', '_type')
    ]
