# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0006_check_zero_amount_20160907_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('description', models.TextField(blank=True, default='')),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hordak.StatementImport')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='has_statements',
            field=models.BooleanField(default=False, help_text='Does this account have statements to reconcile against. This is typically the case for bank accounts.'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statementline',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, help_text='Reconcile this statement line to this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, to='hordak.Transaction'),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='hordak.Account'),
        ),
    ]
