# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hordak", "0007_auto_20161209_0111")]

    operations = [migrations.RenameField("Account", "has_statements", "is_bank_account")]
