# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hordak", "0007_check_leg_and_account_currency_match")]

    operations = [
        migrations.RunSQL(
            """
                ALTER TABLE hordak_account
                ADD CONSTRAINT bank_accounts_are_asset_accounts
                CHECK (is_bank_account = FALSE OR type = 'AS')
            """,
            """ALTER TABLE hordak_account DROP CONSTRAINT bank_accounts_are_asset_accounts""",
        )
    ]
