# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 23:54
from __future__ import unicode_literals

from django.db import migrations
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0009_auto_20160910_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=None, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='leg',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=None, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=None, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='statementline',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=None, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=None, null=True, unique=False),
        ),
    ]
