# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 00:05
from __future__ import unicode_literals

import django_smalluuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0011_auto_20160913_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statementimport',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), null=False, unique=True),
        ),
    ]
