# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hordak", "0011_auto_20170225_2222")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="full_code",
            field=models.CharField(db_index=True, default="", max_length=100),
        )
    ]
