# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0013_trigger_full_account_code'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='account',
        #     name='full_code',
        #     field=models.CharField(db_index=True, max_length=100, unique=True),
        # ),
    ]
