# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0016_check_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'date'},
        ),
    ]
