# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hordak", "0017_auto_20171203_1516")]

    operations = [
        migrations.RenameModel(old_name="TransactionImport", new_name="TransactionCsvImport"),
        migrations.RenameModel(
            old_name="TransactionImportColumn", new_name="TransactionCsvImportColumn"
        ),
    ]
