# Generated by Django 2.0.8 on 2018-08-29 14:05

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields

from hordak.defaults import DECIMAL_PLACES, MAX_DIGITS


class Migration(migrations.Migration):

    dependencies = [("hordak", "0024_auto_20180827_1148")]

    operations = [
        migrations.AlterField(
            model_name="leg",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=DECIMAL_PLACES,
                max_digits=MAX_DIGITS,
                default=Decimal("0.0"),
                default_currency="EUR",
                help_text="Record debits as positive, credits as negative",
            ),
        ),
        migrations.AlterField(
            model_name="statementline",
            name="amount",
            field=models.DecimalField(decimal_places=DECIMAL_PLACES, max_digits=MAX_DIGITS),
        ),
    ]
