# Generated by Django 2.0.8 on 2018-08-29 14:05

from django.conf import settings
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0024_auto_20180827_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=getattr(settings, 'HORDAK_DECIMAL_PLACES', 2), default=Decimal('0.0'), default_currency='EUR', help_text='Record debits as positive, credits as negative', max_digits=getattr(settings, 'HORDAK_MAX_DIGITS', 13)),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='amount',
            field=models.DecimalField(decimal_places=getattr(settings, 'HORDAK_DECIMAL_PLACES', 2), max_digits=getattr(settings, 'HORDAK_MAX_DIGITS', 13)),
        ),
    ]
