# Generated by Django 4.1 on 2022-08-22 14:00

import djmoney.models.fields
from django.db import migrations
import hordak.models.core
import hordak.defaults


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0029_alter_leg_amount_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leg",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=hordak.models.core.get_currency_choices(),
                default=hordak.defaults.get_internal_currency,
                editable=False,
                max_length=3,
            ),
        ),
    ]
