# Generated by Django 4.0.8 on 2022-11-03 22:00

import django.contrib.postgres.fields
from django.db import migrations, models

import hordak.models


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0032_check_account_type_big_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currencies",
            field=models.JSONField(
                default=hordak.models.core.project_currencies,
                verbose_name="currencies",
            ),
        ),
    ]
