# Generated by Django 4.1.7 on 2023-05-02 11:58

import django.contrib.postgres.fields
import djmoney.models.fields
from django.db import migrations, models
import hordak.models.core
import hordak.defaults

import hordak.models


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0033_alter_account_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currencies",
            field=models.JSONField(
                verbose_name="currencies",
            ),
        ),
        migrations.AlterField(
            model_name="leg",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=hordak.models.core.get_currency_choices(),
                default=hordak.defaults.get_internal_currency,
                editable=False,
                max_length=3,
            ),
        ),
    ]
