# Generated by Django 4.2 on 2023-05-16 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "hordak",
            "0036_remove_currencies_and_rename_account_currencies_json_to_currencies",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION check_leg_and_account_currency_match()
                RETURNS trigger AS
            $$
            DECLARE

            BEGIN

                IF (TG_OP = 'DELETE') THEN
                    RETURN OLD;
                END IF;

                PERFORM * FROM hordak_account WHERE id = NEW.account_id AND currencies::jsonb @> to_jsonb(ARRAY[NEW.amount_currency]::text[]);

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Destination account does not support currency %', NEW.amount_currency;
                END IF;

                RETURN NEW;
            END;
            $$
            LANGUAGE plpgsql
            """,
            "DROP FUNCTION check_leg_and_account_currency_match()",
        ),
    ]
