# Generated by Django 4.2.3 on 2023-08-23 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0035_runningtotal"),
        ("hordak", "0037_auto_20230516_0142"),
    ]

    operations = []
