# Generated by Django 4.2.4 on 2023-08-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hordak', '0037_auto_20230516_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
