# Generated by Django 4.2.8 on 2024-01-05 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0035_runningtotal"),
        ("hordak", "0037_auto_20230516_0142"),
    ]

    operations = []
