# Generated by Django 4.2.4 on 2023-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0038_transaction_related_object_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
