# Generated by Django 4.2.3 on 2024-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0039_recreate_update_full_account_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
