# Generated by Django 5.0.6 on 2024-05-27 17:51

import django.db.models.functions.math
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0040_alter_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="accounting_amount",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.math.Abs(models.F("amount")),
                help_text="Amount adheres to double-entry accounting rules.",
                output_field=djmoney.models.fields.MoneyField(
                    decimal_places=6, max_digits=20
                ),
                verbose_name="Accounting Amount",
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="accounting_type",
            field=models.GeneratedField(
                choices=[("DR", "Debit"), ("CR", "Credit")],
                db_index=True,
                db_persist=True,
                expression=models.Case(
                    models.When(amount__gt=0, then=models.Value("CR")),
                    default=models.Value("DR"),
                ),
                null=True,
                output_field=models.CharField(max_length=2),
                verbose_name="Debit or Credit. Adheres to accounting rules.",
            ),
        ),
    ]
