# Generated by Django 5.0.6 on 2024-06-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0041_auto_20240528_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="code"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="full_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="full_code",
            ),
        ),
    ]
