# Generated by Django 5.0.6 on 2024-06-26 16:33

import djmoney.models.fields
from django.db import migrations, models

import hordak.defaults
import hordak.models.core
from hordak.defaults import DECIMAL_PLACES, MAX_DIGITS


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0043_hordak_leg_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(editable=False, verbose_name="uuid")),
                (
                    "date",
                    models.DateField(
                        help_text="The date on which this transaction leg occurred",
                        verbose_name="date",
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=hordak.models.core.get_currency_choices(),
                        default=hordak.defaults.get_internal_currency,
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=DECIMAL_PLACES,
                        default_currency=hordak.defaults.get_internal_currency,
                        max_digits=MAX_DIGITS,
                        verbose_name="amount",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DR", "Debit"), ("CR", "Credit")],
                        help_text="Type of this transaction leg: debit or credit",
                        max_length=2,
                        verbose_name="type",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=DECIMAL_PLACES,
                        help_text="Amount of this credit, or NULL if not a credit",
                        max_digits=MAX_DIGITS,
                        verbose_name="credit amount",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=DECIMAL_PLACES,
                        help_text="Amount of this debit, or NULL if not a debit",
                        max_digits=MAX_DIGITS,
                        verbose_name="debit amount",
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(
                        decimal_places=DECIMAL_PLACES,
                        help_text="Account balance following this transaction. For multiple-currency accounts this will be the balance of the same currency as the leg amount.",
                        max_digits=MAX_DIGITS,
                        verbose_name="account balance",
                    ),
                ),
                ("leg_description", models.TextField(verbose_name="leg description")),
                (
                    "transaction_description",
                    models.TextField(verbose_name="transaction description"),
                ),
            ],
            options={
                "db_table": "hordak_leg_view",
                "managed": False,
            },
        ),
    ]
