# Generated by Django 5.0.6 on 2024-06-26 16:33

from django.db import migrations, models

from hordak.models import account_default_currencies


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0044_legview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currencies",
            field=models.JSONField(
                db_index=True,
                default=account_default_currencies,
                verbose_name="currencies",
            ),
        ),
    ]
