# Generated by Django 5.0.6 on 2024-06-26 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0045_alter_account_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="leg",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="statementimport",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="statementline",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncsvimport",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncsvimportcolumn",
            name="to_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-- Do not import --"),
                    ("date", "Date"),
                    ("amount", "Amount"),
                    ("amount_out", "Amount (money out only)"),
                    ("amount_in", "Amount (money in only)"),
                    ("description", "Description / Notes"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Is",
            ),
        ),
    ]
