# Generated by Django 4.2 on 2024-06-28 19:02
from pathlib import Path

from django.db import migrations

from hordak.utilities.migrations import (
    migration_operations_from_sql,
    select_database_type,
)

PATH = Path(__file__).parent


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0047_get_balance"),
    ]

    # TODO: TEST!

    operations = select_database_type(
        postgresql=migration_operations_from_sql(
            PATH / "0048_hordak_transaction_view.pg.sql"
        ),
        mysql=migration_operations_from_sql(
            PATH / "0048_hordak_transaction_view.mysql.sql"
        ),
    )
