# Generated by Django 5.1b1 on 2024-07-01 05:12

import djmoney.models.fields
from django.db import migrations

import hordak.defaults
import hordak.models.core
from hordak.defaults import DECIMAL_PLACES, MAX_DIGITS


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0049_transactionview"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="credit",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_field_name="currency",
                decimal_places=DECIMAL_PLACES,
                default=None,
                default_currency=hordak.defaults.get_internal_currency,
                help_text="Amount of this credit, or NULL if not a credit",
                max_digits=MAX_DIGITS,
                null=True,
                verbose_name="credit amount",
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="debit",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_field_name="currency",
                decimal_places=DECIMAL_PLACES,
                default=None,
                default_currency=hordak.defaults.get_internal_currency,
                help_text="Amount of this debit, or NULL if not a debit",
                max_digits=MAX_DIGITS,
                null=True,
                verbose_name="debit amount",
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="currency",
            field=djmoney.models.fields.CurrencyField(
                choices=hordak.models.core.get_currency_choices(),
                default=hordak.defaults.get_internal_currency,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
