# Generated by Django 5.1b1 on 2024-07-01 05:19
from pathlib import Path

from django.db import migrations

from hordak.utilities.migrations import (
    migration_operations_from_sql,
    select_database_type,
)

PATH = Path(__file__).parent


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0051_amount_to_debit_credit_data"),
    ]

    operations = select_database_type(
        postgresql=migration_operations_from_sql(
            PATH / "0052_amount_to_debit_credit_sql.pg.sql"
        ),
        mysql=migration_operations_from_sql(
            PATH / "0052_amount_to_debit_credit_sql.mysql.sql"
        ),
    )
