# Generated by Django 5.1b1 on 2024-07-01 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0051_amount_to_debit_credit_data"),
    ]

    operations = []
