# Generated by Django 5.0.6 on 2024-08-29 17:50
from pathlib import Path

from django.db import migrations

from hordak.utilities.migrations import (
    select_database_type,
    migration_operations_from_sql,
)

PATH = Path(__file__).parent


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0053_remove_leg_amount_remove_leg_amount_currency"),
    ]

    operations = migration_operations_from_sql(
        PATH / "0054_check_debit_credit_positive.sql"
    )
