# Generated by Django 5.1 on 2026-03-22

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models

import hordak.defaults
import hordak.models.core
from hordak.defaults import DECIMAL_PLACES, DEFAULT_CURRENCY, MAX_DIGITS


class Migration(migrations.Migration):
    dependencies = [
        ("hordak", "0054_check_debit_credit_positive"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=15)),
                (
                    "balance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=hordak.models.core.get_currency_choices(),
                        default=DEFAULT_CURRENCY,
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=DECIMAL_PLACES,
                        default_currency=DEFAULT_CURRENCY,
                        max_digits=MAX_DIGITS,
                        null=True,
                    ),
                ),
                ("includes_leg_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_totals",
                        to="hordak.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Running Total",
                "verbose_name_plural": "Running Totals",
                "indexes": [
                    models.Index(
                        fields=["account", "currency", "-includes_leg_id"],
                        name="hordak_runtot_acc_cur_ilid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="leg",
            index=models.Index(
                fields=["account", "-id"],
                name="hordak_leg_acc_id_desc_idx",
            ),
        ),
    ]
